const colors = [
    { label: 'Amarelo', value: '#FFFF00' },
    { label: 'Amarelo Limão', value: '#FFFACD' },
    { label: 'Aquamarine', value: '#7FFFD4' },
    { label: 'Aqua', value: '#00FFFF' },
    { label: 'Azul', value: '#0000FF' },
    { label: 'Azul Arroxeado', value: '#8A2BE2' },
    { label: 'Azul Celeste', value: '#87CEEB' },
    { label: 'Azul Marinho', value: '#000080' },
    { label: 'Bisque', value: '#FFE4C4' },
    { label: 'Bordo', value: '#800000' },
    { label: 'Caqui', value: '#F0E68C' },
    { label: 'Cinza', value: '#808080' },
    { label: 'Cinza Claro', value: '#D3D3D3' },
    { label: 'Coral', value: '#FF7F50' },
    { label: 'Creme', value: '#FFFDD0' },
    { label: 'Chocolate', value: '#D2691E' },
    { label: 'Dourado', value: '#FFD700' },
    { label: 'Esmeralda', value: '#00C957' },
    { label: 'Fogo', value: '#E25822' },
    { label: 'Fúcsia', value: '#FF00FF' },
    { label: 'Hortelã', value: '#98FF98' },
    { label: 'Índigo', value: '#4B0082' },
    { label: 'Laranja Escuro', value: '#FF8C00' },
    { label: 'Laranja', value: '#FFA500' },
    { label: 'Lavanda', value: '#E6E6FA' },
    { label: 'Lilás', value: '#C8A2C8' },
    { label: 'Limão', value: '#00FF00' },
    { label: 'Linho', value: '#FAF0E6' },
    { label: 'Marrom', value: '#A52A2A' },
    { label: 'Melancia', value: '#FC6C85' },
    { label: 'Oliva', value: '#808000' },
    { label: 'Orquídea', value: '#DA70D6' },
    { label: 'Peru', value: '#CD853F' },
    { label: 'Pêssego', value: '#FFE5B4' },
    { label: 'Prata', value: '#C0C0C0' },
    { label: 'Preto', value: '#000000' },
    { label: 'Rosa Claro', value: '#FFB6C1' },
    { label: 'Rosa', value: '#FFC0CB' },
    { label: 'Roxo', value: '#800080' },
    { label: 'Rubi', value: '#E0115F' },
    { label: 'Salmão', value: '#FA8072' },
    { label: 'Teal', value: '#008080' },
    { label: 'Tomate', value: '#FF6347' },
    { label: 'Turquesa', value: '#40E0D0' },
    { label: 'Verde Lima', value: '#32CD32' },
    { label: 'Verde Mar', value: '#2E8B57' },
    { label: 'Verde Musgo', value: '#ADFF2F' },
    { label: 'Verde', value: '#008000' },
    { label: 'Vermelho', value: '#FF0000' }
];



module.exports = {
    colors
}